// Generated by CoffeeScript 1.9.1

/*
	web context router
 */
var exports;

exports = module.exports = function(app, express) {
  /*
  var demo, manager, root, www;
  manager = {};
  console.log("js");
  root = express();
  app.use("/", function(req, res, next) {

    next();
  });

  www = express();
  root.use("www", www);
  app.use(www.path(), www);
  require("./www/index.router")(www, manager);
  demo = express();
  root.use("demo", demo);
  app.use(demo.path(), demo);
  require('./demo/index.router')(demo, manager);
  */
    var manager={};
    var root = express();
    app.use("/", root);
    root.use(function(req, res, next) {
        console.log("root")
        next();
    });
    root.all("/", function(req, res) {
     //   res.send("index.html");
    });
    var www=express();
    root.use("www",www);
    app.use(www.path(),www);
    require('./www/index.router')(www,manager); 
    var demo=express();
    root.use("demo",demo);
    app.use(demo.path(),demo);
    require('./demo/index.router')(demo,manager); 
};
