// Generated by CoffeeScript 1.9.1
var exports;

exports = module.exports = function(router, manager) {
  router.use(function(req, res, next) {
    res.addAttr("ctx", "");
    next();
  });
  router.all("/", function(req, res, next) {
    res.render("demo/views/index");
  });
  router.all("/demo.ftl", function(req, res, next) {
    res.render("demo/views/demo.ftl", {
      user: {
        username: "jaxchow"
      }
    });
  });
  router.all("/demo.html", function(req, res, next) {
    res.render("demo/view/demo.html", {
      user: {
        username: "jaxchow"
      }
    });
  });
};
